### ISSUE TITLE
Ruby error after install of plugin

### ISSUE THREAD

**Issue by rogermartensson** [Undev/redmine_skype_link#3]
Got this when I installed the new plugin.

The error was found in patcher.rb.

``private method `prepend' called for RedCloth3:Class (NoMethodError)``

Did find a similar error while googling and the solution there was to use ".send".
After changing:
``          target.prepend, patch``

to 
``target.send :prepent, path``

The error disappeared and I can't get it back even after returning the line to it's previous value.

This on ubuntu ruby 1.9.x and ruby 2.0.

**Comment by nodecarter** [comment]
Hi @rogermartensson ,
Ruby 1.9.x does not support anymore.
The latest version of this plugin was tested on the Ruby 2.3.1 where Module#prepend already a public method. I recommend to upgrade your ruby or use old versions of this plugin.
